config/routes.rb
Rails.application.routes.draw do
  root "links#index"

  resources :users, only: [:new, :create]
  resources :links, only: [:index, :create, :update, :edit]

  get "/enter", to: "sessions#enter"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user

  validates :url, :url => true
  validates :title, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :links

  validates :email, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :unauthenticated_user,
                :current_user

  def unauthenticated_user
    redirect_to enter_path unless current_user
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :unauthenticated_user

  def index
    @link = Link.new
    @links = current_user.links
  end

  def create
    @link = Link.new(link_params)
    if @link.save
      current_user.links << @link
    else
      flash[:errors] = @link.errors.full_messages.join(", ")
    end
    redirect_to root_path
  end

  def edit
    @link = Link.find(params[:id])
  end

  def update
    @link = Link.find(params[:id])
    @link.update_attributes(link_params)
    if @link.save
      redirect_to root_path
    else
      flash[:errors] = @link.errors.full_messages.join(", ")
      redirect_to edit_link_path
    end
  end

  private

    def link_params
      params.require(:link).permit(:url, :title, :read)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash.now[:error] = "Your email or password is incorrect"
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to login_path
  end

  def enter
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash.now[:errors] = @user.errors.full_messages.join(", ")
      render :new
    end
  end

  private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thoughtbox</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1"></head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.min.css">

<body>

  <% if current_user %>
    <%= link_to "Sign Out", logout_path, method: :delete %>
  <% end %>

  <% flash.each do |type, msg| %>
    <%= content_tag :div, msg %>
  <% end %>

<%= yield %>

  <!--Import jQuery before materialize.js-->
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>

</body>
</html>

app/views/links/edit.html.erb
<h2>Edit the link here!</h2>

<%= render partial: "/partials/link_form" %>

app/views/links/index.html.erb
<h3>Submit your new link here!</h3>

<%= render partial: "/partials/link_form" %>

<br/>
<br/>
<br/>
<br/>

<h4>Search the Links</h4>
<div class="filter">
  <form id="link_filter" action="index.html" method="post">
    Search:
    <input type="test" name="name" value="">
  </form>
</div>

<br/>
<br/>
<br/>

<h3>All of the links belonging to <%= current_user.email %>!</h3>

<% @links.each do |link| %>
  <div class="link">
    <div class="title">
      <%= link.title %>
    </div>
    <%= link_to link.url, "#{link.url}", class: :url %> -
    <% if link.read %>
      <%= link_to "Mark as Unread", link_path(link, link: {read: false}), method: :patch, class: :read %>
    <% else %>
      <%= link_to "Mark as Read", link_path(link, link: {read: true}), method: :patch, class: :unread %>
    <% end %> -
    <%= link_to "Edit", edit_link_path(link) %>
    <br/>
  </div>
<% end %>

app/views/partials/_link_form.html.erb
<%= form_for(@link) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :url %>
  <%= f.text_field :url %>

  <%= f.submit "Submit" %>
<% end %>

app/views/users/new.html.erb
<h1>Enter your info and sign up here!</h1>
<h4>or <%= link_to "login", login_path %></h4>

<%= form_for(@user) do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Submit" %>
<% end %>